import { helper } from '@ember/component/helper';

export const keywords = [
  ['100% Affordable', 'Housing is considered affordable when a household spends no more than one-third of its income on rent. This is usually pursuant to HPD (Housing Preservation & Development) financing or a voluntary pledge on the part of the applicant; existing City programs cannot require all units to be affordable.'],
  ['Affordable Housing', 'Housing is considered affordable when a household spends no more than one-third of its income on rent. There are Voluntary and Mandatory Inclusionary (affordable) Housing areas mapped throughout various places in the city. MIH (Mandatory Inclusionary Housing) is required when there is a zoning change that would allow a larger building/more dense development/residential use. '],
  ['BSA', 'The Board of Standards and Appeals (BSA), composed of five commissioners appointed by the Mayor, reviews and grants applications for special permits, as prescribed in the Zoning Resolution, for certain proposed developments and uses. The BSA also grants variances for zoning lots with irregular physical conditions where construction might not otherwise be possible. In addition, the Board hears and decides appeals to determinations by the Department of Buildings.'],
  ['Café', 'A sidewalk cafe is a portion of an eating or drinking estab­lishment that is located on a public sidewalk. Sidewalk cafe regulations are administered by the Department of Consumer Affairs.'],
  ['CFLS', ''],
  ['CND', 'A Negative Declaration is a determination by the lead agency that an action will not result in a significant adverse environmental impact and consequently no EIS will be prepared. A Conditional Negative Declaration signifies that the project will not result in an adverse impact as long as specified measures are undertaken. '],
  ['Com. Overlay', 'A Commercial Overlay is a C1 or C2 district mapped within residential districts to serve local retail needs (grocery stores, dry cleaners, restaurants, for example). '],
  ['Cont. Use', 'Continued Use by the city of a privately owned building.'],
  ['Conversion', 'A conversion is a change of a building’s use to another use.'],
  ['Create MIH Area', 'Mandatory Inclusionary Housing, or MIH, requires affordable housing as part of all residential development above a certain size in applicable areas.'],
  ['Create/Modify Privately Owned Public Space (POPS)', 'Privately Owned Public Spaces (POPS) are an amenity provided and maintained by a developer for public use, in exchange for additional floor area.'],
  ['Create/Modify Publicly Accessible Waterfront Space', ''],
  ['Create/Modify Public Open Space', 'Public open space is the part of a residential zoning lot (which may include courts or yards) that is open and unob­structed from its lowest level to the sky, except for specific permitted obstructions, and accessible to and usable by all persons.'],
  ['Day Care', ''],
  ['E-Designation', 'An “E” designation assigned to a zoning lot indicates a site where environmental requirements must be satisfied before a building permit may be issued for any develop­ment, enlargement or change of use.'],
  ['EIS', 'An Environmental Impact Statement (EIS) is a document prepared to enable the public and decision-makers to understand the nature and consequences of the environmental impacts of a proposed action.'],
  ['Environmental Impact Statement (EIS)-1', 'An Environmental Impact Statement (EIS) is a document prepared to enable the public and decision-makers to understand the nature and consequences of the environmental impacts of a proposed action.'],
  ['Fast Track', 'Fast Track is an expedited review process for certain qualifying applications that do not require detailed environmental review.'],
  ['Ferries', ''],
  ['FRESH', 'A FRESH food store is a full-line grocery store, established in underserved neighborhoods through zoning incentives, that promotes the sale of fresh food products.'],
  ['Historic District', "Historic Districts are areas of the city that possess architectural and historical significance and a distinct 'sense of place' according to the Landmarks Preservation Commission."],
  ['Hotel', ''],
  ['Housing', ''],
  ['IBZ', 'Industrial Business Zones (IBZ) are areas where expanded business services are available for industrial and manufacturing businesses.'],
  ['Includes BSA', 'The Board of Standards and Appeals (BSA), composed of five commissioners appointed by the Mayor, reviews and grants applications for special permits, as prescribed in the Zoning Resolution, for certain proposed developments and uses. The BSA also grants variances for zoning lots with irregular physical conditions where construction might not otherwise be possible. In addition, the Board hears and decides appeals to determinations by the Department of Buildings.'],
  ['Inclusionary Housing Deep', 'The Inclusionary Housing Program provides optional floor area incentives in exchange for the creation or preservation of affordable housing, on or off-site, pre­dominantly for low-income households.'],
  ['Inclusionary Housing Option 1', 'The Inclusionary Housing Program provides optional floor area incentives in exchange for the creation or preservation of affordable housing, on or off-site, pre­dominantly for low-income households.'],
  ['Inclusionary Housing Option 2', 'The Inclusionary Housing Program provides optional floor area incentives in exchange for the creation or preservation of affordable housing, on or off-site, pre­dominantly for low-income households.'],
  ['Industrial', ''],
  ['Infrastructure', ''],
  ['JIA', 'Joint Interest Areas (JIA) are public parks, waterways, major governmental installations and similar land uses which are not located within bounding community districts. Examples are Central Park, Van Cortlandt Park, LaGuardia and JFK Airports.'],
  ['JLWQA', 'Joint living-work quarters for artists (JLWQA) are spaces in non­residential buildings used for living quarters and work space by artists and their households.'],
  ['Joint CEQR Review', 'City Environmental Quality Review (CEQR) is the process by which New York City agencies determine what effect, if any, a discretionary action they approve may have upon the environment. A Joint CEQR Review refers to a review that involves multiple city agencies.'],
  ['Landmark', ''],
  ['Large-scale Development', 'A large-scale development is a development on a large zoning lot or several zoning lots planned as a unit that are contiguous or only separated by a street. In order to promote good site planning for these types of developments and their surrounding neighborhoods, given this unique nature of scale, the City Planning Commission (CPC) may modify the underlying zoning district rules to allow greater flexibility of bulk and open space on the site.'],
  ['LSGD', 'A large-scale general development (LSGD) is a development or enlargement located in a medium- or high-density commercial or manufacturing district that must contain uses allowed by the underlying zoning district.'],
  ['Major Initiative', ''],
  ['Major Mod', 'If a modification would increase the extent of a previously granted waiver of zoning regulations, or require new waivers or other discretionary land use approvals not included within the prior ULURP, it is referred to as a ‘major’ modification, a term used to indicate that initiation of a new ULURP application is required for its review and approval.'],
  ['Mass Transit Improvements', ''],
  ['MIH Deep Affordability', 'Mandatory Inclusionary Housing, or MIH, requires affordable housing as part of all residential development above a certain size in applicable areas. Deep affordability requires a 20 percent set aside for households with incomes at an average of 40 percent Area Median Income (AMI).'],
  ['MIH Option 1', 'Mandatory Inclusionary Housing, or MIH, requires affordable housing as part of all residential development above a certain size in applicable areas. Option 1 requires that at least 25 percent of the residential floor area be provided as housing permanently affordable to households with incomes at an average of 60 percent of the area median income (AMI). Within that 25 percent, at least 10 percent of the square footage must be used for units affordable to residents with household incomes at an average of 40 percent of the AMI, with no unit targeted to households with incomes exceeding 130 percent of the AMI.'],
  ['MIH Option 2', 'Mandatory Inclusionary Housing, or MIH, requires affordable housing as part of all residential development above a certain size in applicable areas. Option 2 requires that 30 percent of residential floor area be devoted to housing units affordable to residents with household incomes at an average of 80 percent of the area median income (AMI). No more than three income bands can be used to average out to the 80 percent, and no income band can exceed 130 percent of the AMI. '],
  ['MIH Workforce', 'Mandatory Inclusionary Housing (MIH) requires affordable housing as part of all residential development above a certain size in applicable areas. Workforce Option requires a 30 percent set aside at an average of 115 percent Area Median Income (AMI), with a minimum of 5 percent at 70 percent AMI and 5 percent at 90 percent AMI.'],
  ['Minor Modification', 'In a Minor Modification, the proposed changes may alter elements of the prior approval, but without increasing the extent of any waiver or modification of the underlying zoning regulations granted under the prior ULURP approvals, and without requiring any new waivers or modifications of zoning regulations.'],
  ['Mitigation', 'Hazard mitigation is any cost-effective and sustained action taken to reduce the long-term risk to human life, property, and infrastructure from hazards.'],
  ['Modification', 'Following ULURP approval of an application, property owners and developers sometimes seek modifications to the approval. The nature and extent of the proposed modifications may vary significantly, in some cases amounting to small adjustments and in other cases resulting in larger changes to a project.'],
  ['M to M', 'Rezoned Mixed Use to different Mixed Use'],
  ['M to R', 'Rezoned Manufacturing to Residential'],
  ['MX', 'A mixed use district is a special purpose district where one set of regulations applies to many different areas shown on the zoning maps as MX with a numerical suffix (MX-8, for example). In MX districts, an M1 district is paired with a residential district (M1-2/R6, for example) and new residential and non-residential uses are permit­ted as-of-right within the same building. In this district, a building that contains a residential use and any other use is a mixed use building.'],
  ['New Open Space', 'Open space is the part of a residential zoning lot (which may include courts or yards) that is open and unob­structed from its lowest level to the sky, except for specific permitted obstructions, and accessible to and usable by all persons occupying dwelling units on the zoning lot. Depending upon the district, the amount of required open space is determined by the open space ratio, minimum yard regulations or by maximum lot coverage.'],
  ['New Public Park', 'A public park is any publicly owned park, playground, beach, parkway, or roadway within the jurisdiction and control of the New York City Commissioner of Parks & Recreation. Typically, public parks are not subject to zoning regulations.'],
  ['New SD', 'Special Districts, or Special Purpose Districts, are usually created where the conditions in a place, or a set of similar places, warrant modification of zoning regulations. They are established to advance goals such as preserving natural features, encouraging mixed uses, or promoting economic development/revitalization. '],
  ['New ZD', 'New Zoning District'],
  ['New Zoning District', ''],
  ['Office', ''],
  ['Open Space', 'Open space is the part of a residential zoning lot (which may include courts or yards) that is open and unob­structed from its lowest level to the sky, except for specific permitted obstructions, and accessible to and usable by all persons occupying dwelling units on the zoning lot. Depending upon the district, the amount of required open space is determined by the open space ratio, minimum yard regulations or by maximum lot coverage.'],
  ['Parking', ''],
  ['Parking Facility', ''],
  ['Parking Garage/Lot Application', ''],
  ['POPS', 'Privately Owned Public Spaces (POPS) are an amenity provided and maintained by a developer for public use, in exchange for additional floor area.'],
  ['Project Area Includes/Adjacent to Landmark', ''],
  ['Project Will Be 100% Affordable', 'Housing is considered affordable when a household spends no more than one-third of its income on rent. This is usually pursuant to HPD (Housing Preservation & Development) financing or a voluntary pledge on the part of the applicant; existing City programs cannot require all units to be affordable.'],
  ['Renewal', 'Many times special permit actions or other land use approvals are approved for a limited time period, and may require renewal should development under the approvals be delayed or take longer than anticipated.'],
  ['Restrictive Declaration Modification', 'A restrictive declaration is a covenant running with the land that binds the present and future owners of the prop­erty. Restrictive declarations are used to implement the conditions of a land use approval or ensure implementation of environmental mitigations and project components.'],
  ['Retail', ''],
  ['RFP', 'Request for Proposal'],
  ['RLS', 'Residential Listing Service'],
  ['School', ''],
  ['Senior Center', ''],
  ['Senior Housing', ''],
  ['SNAD', 'The purpose of the Special Natural Area District (SNAD) is to guide new development and site alterations in areas endowed with unique natural characteristics, including forests, rock outcrops, steep slopes, creeks and a variety of botanic and aquatic environments.'],
  ['Special Permit (Bulk)', 'A special permit is a discretionary action by the City Planning Commission (CPC), subject to ULURP review, or the Board of Standards and Appeals (BSA), which may modify use, bulk or parking regulations if certain condi­tions and findings specified in the Zoning Resolution are met. Applications for special permits under CPC jurisdiction generally concern use or bulk modifications with potential for greater land use impacts than those reviewed by the BSA.'],
  ['Special Permit Renewal', 'A special permit is a discretionary action by the City Planning Commission (CPC), subject to ULURP review, or the Board of Standards and Appeals (BSA), which may modify use, bulk or parking regulations if certain condi­tions and findings specified in the Zoning Resolution are met. Applications for special permits under CPC jurisdiction generally concern use or bulk modifications with potential for greater land use impacts than those reviewed by the BSA.'],
  ['Special Permit (Use)', 'A special permit is a discretionary action by the City Planning Commission (CPC), subject to ULURP review, or the Board of Standards and Appeals (BSA), which may modify use, bulk or parking regulations if certain condi­tions and findings specified in the Zoning Resolution are met. Applications for special permits under CPC jurisdiction generally concern use or bulk modifications with potential for greater land use impacts than those reviewed by the BSA.'],
  ['Split-lot', 'Split lots are lots mapped within two different zoning districts. '],
  ['Subst. Compl.', 'In some cases, modifications to an approval may be so small that they do not require any actual modification to the prior ULURP approvals. Adjustments that do not relate to a zoning waiver or modification granted during the land use review process may be determined to be in “substantial compliance” with the approvals and require no further action by the City Planning Commission or City Council. '],
  ['Supportive Housing', 'The Supportive Housing Loan Program (SHLP) of the New York City Department of Housing Preservation and Development (HPD) provides funding to non-profit sponsors to develop permanent housing with on-site services for special populations. '],
  ['TDR', 'A Transfer of Development Rights (TDR) allows for the transfer of unused development rights from one zoning lot to another in limited circumstances, usually to promote the preservation of historic build­ings, open space or unique cultural resources.'],
  ['WAP', 'A Waterfront Access Plan (WAP) is a detailed framework, set forth in the Zoning Resolution, that tailors waterfront bulk regulations and public access requirements to the specific conditions of a particular waterfront parcel. Development of individual waterfront parcels governed by the plan trig­gers a requirement to build and maintain public access areas in accordance with the WAP.'],
  ['Waterfront', 'A waterfront area is the geographical area adjacent to a body of water at least 100 feet wide, comprising all blocks between the pierhead line and a parallel line 800 feet land­ward from the shoreline. Blocks within the waterfront area are subject to waterfront zoning regulations.'],
  ['Waterfront Access Plan (WAP) Applicable', 'A Waterfront Access Plan (WAP) is a detailed framework, set forth in the Zoning Resolution, that tailors waterfront bulk regulations and public access requirements to the specific conditions of a particular waterfront parcel. Development of individual waterfront parcels governed by the plan trig­gers a requirement to build and maintain public access areas in accordance with the WAP.'],
  ['Waterfront Block or Lot', 'A waterfront block, waterfront public park or waterfront zoning lot is a block, public park or zoning lot in the waterfront area that is adjacent to or intersected by the shoreline.'],
  ['Waterfront (no open space)', 'A waterfront area is the geographical area adjacent to a body of water at least 100 feet wide, comprising all blocks between the pierhead line and a parallel line 800 feet land­ward from the shoreline. Blocks within the waterfront area are subject to waterfront zoning regulations.'],
  ['Waterfront (other)', 'A waterfront area is the geographical area adjacent to a body of water at least 100 feet wide, comprising all blocks between the pierhead line and a parallel line 800 feet land­ward from the shoreline. Blocks within the waterfront area are subject to waterfront zoning regulations.'],
  ['Waterfront (WPAA)', 'A Waterfront Public Access Area (WPAA) is the portion of a waterfront zoning lot where publicly accessible open space is provided to and along the shoreline.'],
  ['Within Industrial Business Zone', 'Industrial Business Zones (IBZ) are areas where expanded business services are available for industrial and manufacturing businesses.'],
  ['Within or Adjacent to Historic District', "Historic Districts are areas of the city that possess architectural and historical significance and a distinct 'sense of place,' and are designated by the Landmarks Preservation Commission."],
  ['Within URA', 'Urban Renewal Area'],
].map(([keyword, tooltip]) => ({ keyword, tooltip }));

export function keywordLookup([keywordTip]) {
  // return all if no arguments are passed
  if (keywordTip === undefined) return keywords;

  const { tooltip } = keywords.find(({ keyword }) => keyword === keywordTip) || '';

  return tooltip;
}

export default helper(keywordLookup);
