[build]
command = "LUPP_ENABLED=false HOST_API=https://zap-api.herokuapp.com.planninglabs.nyc yarn build --environment=production"

[context.master]
command = "HOST_API=https://zap-api.planninglabs.nyc yarn build --environment=production"

[context.develop-future]
command = "HOST_API=https://zap-api.herokuapp.com yarn build --environment=production"
