import Component from '@ember/component';
import { classNames } from '@ember-decorators/component';

export const CdLookup = [
  ['BK01', '1', 'Brooklyn'],
  ['BK02', '2', 'Brooklyn'],
  ['BK03', '3', 'Brooklyn'],
  ['BK04', '4', 'Brooklyn'],
  ['BK05', '5', 'Brooklyn'],
  ['BK06', '6', 'Brooklyn'],
  ['BK07', '7', 'Brooklyn'],
  ['BK08', '8', 'Brooklyn'],
  ['BK09', '9', 'Brooklyn'],
  ['BK10', '10', 'Brooklyn'],
  ['BK11', '11', 'Brooklyn'],
  ['BK12', '12', 'Brooklyn'],
  ['BK13', '13', 'Brooklyn'],
  ['BK14', '14', 'Brooklyn'],
  ['BK15', '15', 'Brooklyn'],
  ['BK16', '16', 'Brooklyn'],
  ['BK17', '17', 'Brooklyn'],
  ['BK18', '18', 'Brooklyn'],
  ['BX01', '1', 'Bronx'],
  ['BX02', '2', 'Bronx'],
  ['BX03', '3', 'Bronx'],
  ['BX04', '4', 'Bronx'],
  ['BX05', '5', 'Bronx'],
  ['BX06', '6', 'Bronx'],
  ['BX07', '7', 'Bronx'],
  ['BX08', '8', 'Bronx'],
  ['BX09', '9', 'Bronx'],
  ['BX10', '10', 'Bronx'],
  ['BX11', '11', 'Bronx'],
  ['BX12', '12', 'Bronx'],
  ['MN01', '1', 'Manhattan'],
  ['MN02', '2', 'Manhattan'],
  ['MN03', '3', 'Manhattan'],
  ['MN04', '4', 'Manhattan'],
  ['MN05', '5', 'Manhattan'],
  ['MN06', '6', 'Manhattan'],
  ['MN07', '7', 'Manhattan'],
  ['MN08', '8', 'Manhattan'],
  ['MN09', '9', 'Manhattan'],
  ['MN10', '10', 'Manhattan'],
  ['MN11', '11', 'Manhattan'],
  ['MN12', '12', 'Manhattan'],
  ['QN01', '1', 'Queens'],
  ['QN02', '2', 'Queens'],
  ['QN03', '3', 'Queens'],
  ['QN04', '4', 'Queens'],
  ['QN05', '5', 'Queens'],
  ['QN06', '6', 'Queens'],
  ['QN07', '7', 'Queens'],
  ['QN08', '8', 'Queens'],
  ['QN09', '9', 'Queens'],
  ['QN10', '10', 'Queens'],
  ['QN11', '11', 'Queens'],
  ['QN12', '12', 'Queens'],
  ['QN13', '13', 'Queens'],
  ['QN14', '14', 'Queens'],
  ['SI01', '1', 'Staten Island'],
  ['SI02', '2', 'Staten Island'],
  ['SI03', '3', 'Staten Island'],
  ['SI95', '95', 'Staten Island'],
].map(([code, num, boro]) => ({ code, num, boro, searchField: `${boro} ${num}` }));

export const actions = [
  ['PP','Disposition of Non-Residential City-Owned Property'],
  ['MC','Major Concessions'],
  ['ZP','Parking Special Permit/Incl non-ULURP Ext'],
  ['ZD','Amended Restrictive Declaration'],
  ['ZX','Counsel\'s Office - Rules of Procedure'],
  ['MF','Franchise Applic - Not Sidewalk Café'],
  ['ME','Easements (Administrative)'],
  ['PS','Site Selection (City Facility) '],
  ['PN','Negotiated Disposition of City Property'],
  ['HK','Landmarks - Historic Districts'],
  ['HC','Minor Change'],
  ['MC','Major Concessions'],
  ['HR','Assignments & Transfers'],
  ['HD','Disposition of Urban Renewal Site '],
  ['ZJ','Residential Loft Determination'],
  ['GF','Franchise or Revocable Consent'],
  ['RA','South Richmond District Authorizations'],
  ['ML','Landfill'],
  ['HU','Urban Renewal Plan and Amendments '],
  ['UK','Unknown Action'],
  ['EIS','Environmental Impact Statement '],
  ['RA','South Richmond District Authorizations '],
  ['BF','Business Franchise'],
  ['PD','Amended Drainage Plan'],
  ['PC','Combination Acquisition and Site Selection by the City '],
  ['MM','Change in City Map '],
  ['PP','Disposition of Non-Residential City-Owned Property'],
  ['RS','South Richmond District Special Permits'],
  ['MD','Drainage Plan'],
  ['VT','Cable TV'],
  ['PO','OTB Site Selection'],
  ['ZM','Zoning Map Amendment '],
  ['MY','Administration Demapping'],
  ['MP','Prior Action'],
  ['MA','Assignment/Acquisition'],
  ['RC','South Richmond District Certifications '],
  ['HA','Urban Development Action Area - UDAAP'],
  ['ZL','Large Scale Special Permit'],
  ['BD','Business Improvement Districts '],
  ['PI','Private Improvement'],
  ['PC','Combination Acquisition and Site Selection by the City'],
  ['PS','Site Selection (City Facility)'],
  ['ZS','Zoning Special Permit'],
  ['EU','CEQR Application'],
  ['ME','Easements (Administrative)'],
  ['TL','Leasing of C-O-P By Private Applicants'],
  ['DL','Disposition for Residential Low-Income Use'],
  ['EM','CEQR Application'],
  ['PL','Leasing of Private Property by the City'],
  ['ZA','Zoning Authorization '],
  ['PQ','Acquisition of Property by the City'],
  ['HS','Special District/Mall Plan/REMIC NPA'],
  ['EE','CEQR Application'],
  ['ZC','Zoning Certification'],
  ['EC','Enclosed Sidewalk Cafes'],
  ['HO','Housing Application (Plan and Project)'],
  ['RA','South Richmond District Authorizations'],
  ['PX','Office Space'],
  ['ZM','Zoning Map Amendment'],
  ['PX','Office Space'],
  ['MD','Drainage Plan'],
  ['ZM','Zoning Map Amendment'],
  ['HK','Landmarks - Historic Districts '],
  ['BD','Business Improvement Districts'],
  ['HP','Plan & Project/Land Disposition Agreement (LDA)'],
  ['ZS','Zoning Special Permit'],
  ['EC','Enclosed Sidewalk Cafes '],
  ['PR','Release of City\'s Interest'],
  ['UC','Unenclosed Café'],
  ['ML','Landfill'],
  ['WR','Waterfront Revitalization Program '],
  ['HK','Landmarks - Historic Districts'],
  ['UK','Unknown Action '],
  ['CM','Renewal'],
  ['HG','Urban Renewal Designation'],
  ['HZ','Preliminary Site Approval Application'],
  ['FT','Fast Track '],
  ['MM','Change in City Map'],
  ['LD','Legal Document (NOC, NOR, RD) '],
  ['EN','CEQR Application'],
  ['RC','South Richmond District Certifications'],
  ['EC','Enclosed Sidewalk Cafes'],
  ['ZR','Zoning Text Amendment'],
  ['ZR','Zoning Text Amendment '],
  ['ZC','Zoning Certification'],
  ['ZZ','Site Plan Approval in Natural Area Districts'],
  ['HG','Urban Renewal Designation'],
  ['GF','Franchise or Revocable Consent'],
  ['ZA','Zoning Authorization'],
  ['PE','Exchange of City Property with Private Property'],
  ['ZS','Zoning Special Permit '],
  ['HU','Urban Renewal Plan and Amendments'],
  ['HC','Minor Change'],
  ['DM','Disposition for Residential Not Low-Income Use'],
  ['PQ','Acquisition of Property by the City '],
  ['EB','CEQR Application'],
  ['CP', ''],
  ['HA','Urban Development Action Area - UDAAP '],
  ['HD','Disposition of Urban Renewal Site'],
  ['HN','Urban Development Action Area - UDAAP Non-ULURP '],
  ['ZA','Zoning Authorization'],
  ['SC','Special Natural Area Certifications '],
  ['CS','Substantial Compliance '],
  ['HC','Minor Change '],
  ['PX','Office Space '],
  ['CM','Renewal'],
  ['PP','Disposition of Non-Residential City-Owned Property '],
  ['ZR','Zoning Text Amendment'],
  ['BD','Business Improvement Districts'],
  ['TC','Consent - Sidewalk Café'],
  ['NP','197-A Plan'],
  ['PQ','Acquisition of Property by the City'],
  ['HD','Disposition of Urban Renewal Site'],
  ['Study','Study '],
  ['PS','Site Selection (City Facility)'],
  ['PA','Transfer/Assignment'],
  ['NP','197-A Plan'],
  ['HP','Plan & Project/Land Disposition Agreement (LDA) '],
  ['HL','Housing/Urban Renewal/Pub Ben Corp Lease'],
  ['EAS','Environmental Assessment Statement '],
  ['EF','CEQR Application'],
  ['CM','Renewal '],
  ['PM','Map Change Related to Site Selection'],
  ['MM','Change in City Map'],
  ['EAS','Environmental Assessment Statement'],
  ['HF','Community Dev. Application/Amendment'],
  ['HM','Currently Residential/Not Low-Income'],
  ['HA','Urban Development Action Area - UDAAP'],
  ['RC','South Richmond District Certifications'],
  ['HI','Landmarks - Individual Sites '],
  ['HU','Urban Renewal Plan and Amendments'],
  ['PC','Combination Acquisition and Site Selection by the City'],
  ['ZC','Zoning Certification '],
].map(([code, description]) => ({ code, description }));

@classNames('project-filters')
export default class ProjectFiltersComponent extends Component {
  communityDistrictOptions = CdLookup;
  actionsOptions = actions;
}
