version: 2
jobs:
  nest_tests:
    docker:
      - image: circleci/node:10.18-browsers
    working_directory: ~/repo/server

    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install node deps
          command: |
            yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: run tests
          command: yarn test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  ember_tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.18-browsers
        environment:
          BUILD_CONTEXT: test

    working_directory: ~/repo/client

    steps:
      - checkout:
          path: ~/repo

      - run:
          name: install ember deps
          command: yarn

      # run tests!
      - run:
          name: run tests
          command: COVERAGE=true yarn test

      - run: curl -s https://codecov.io/bash | bash

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  run_tests:
    jobs:
      - nest_tests
      - ember_tests
