dcp_name,
dcp_ceqrnumber,
dcp_ceqrtype,
dcp_projectname,
dcp_projectbrief,
dcp_publicstatus_simp,
dcp_borough,
dcp_ulurp_nonulurp,
dcp_validatedcommunitydistricts,
actiontypes,
dcp_certifiedreferred,
dcp_femafloodzonea,
dcp_femafloodzoneshadedx,
applicants,
lastmilestonedate,
cast(count(dcp_projectid) OVER() as integer) as total_projects,
CASE WHEN c.centroid IS NOT NULL THEN true ELSE false END AS has_centroid,
ARRAY[ST_X(c.centroid), ST_Y(c.centroid)] as center,
string_to_array(ulurpnumbers, ';') as ulurpnumbers
