import { Factory, trait } from 'ember-cli-mirage';
import moment from 'moment';

export default Factory.extend({

  // UPCOMING MILESTONES FOR ALL LUP USERS
  prepareFiledLandUseApplication: trait({
    milestone: '663beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Land Use Application Filed',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 26,
    displayName: 'Land Use Application Filed',
    displayDate: moment().subtract(95, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  landUseFeePaid: trait({
    milestone: '6a3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Land Use Fee Paid',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 28,
    displayName: 'Land Use Fee Paid',
    displayDate: moment().subtract(90, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  eisDraftScopeReview: trait({
    milestone: '7c3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Draft Scope of Work for Environmental Impact Statement Received',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 33,
    displayName: 'Draft Scope of Work for Environmental Impact Statement Received',
    displayDate: moment().subtract(60, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  ceqrFeePayment: trait({
    milestone: '763beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'CEQR Fee Paid',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: moment().subtract(70, 'days'),
    statuscode: 'Completed',
    milestonesequence: 36,
    displayName: 'CEQR Fee Paid',
    displayDate: moment().subtract(70, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  filedEasReview: trait({
    milestone: '783beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Environmental Assessment Statement Filed',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 37,
    displayName: 'Environmental Assessment Statement Filed',
    displayDate: moment().subtract(40, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  eisPublicScopingMeeting: trait({
    milestone: '7e3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Environmental Impact Statement Public Scoping Meeting',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 38,
    displayName: 'Environmental Impact Statement Public Scoping Meeting',
    displayDate: moment().subtract(30, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  finalScopeOfWorkIssued: trait({
    milestone: '823beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Final Scope of Work for Environmental Impact Statement Issued',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 40,
    displayName: 'Final Scope of Work for Environmental Impact Statement Issued',
    displayDate: moment().subtract(30, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  nocOfDraftIssued: trait({
    milestone: '843beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Draft Environmental Impact Statement Completed',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 41,
    displayName: 'Draft Environmental Impact Statement Completed',
    displayDate: moment().subtract(5, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  deisPublicHearingHeld: trait({
    milestone: '863beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Draft Environmental Impact Statement Public Hearing',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 42,
    displayName: 'Draft Environmental Impact Statement Public Hearing',
    displayDate: moment().subtract(20, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  feisPublicSubmittedAndReview: trait({
    milestone: '883beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Final Environmental Impact Statement Submitted',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Completed',
    milestonesequence: 43,
    displayName: 'Final Environmental Impact Statement Submitted',
    displayDate: moment().subtract(10, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  certifiedReferred: trait({
    milestone: '8e3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Application Reviewed at City Planning Commission Review Session',
    plannedstartdate: null,
    plannedenddate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: 'Not Started',
    milestonesequence: 46,
    displayName: 'Application Reviewed at City Planning Commission Review Session',
    displayDate: moment().add(2, 'days'),
    displayDate2: null,
    milestoneoutcome: '',
    milestoneLinks: [],
  }),

  // REVIEW MILESTONES (CB REVIEW WILL BE UPCOMING FOR BP)

  communityBoardReview: trait({
    milestone: '923beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Community Board Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 48,
    displayName: 'Community Board Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  boroughPresidentReview: trait({
    milestone: '943beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Borough President Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 49,
    displayName: 'Borough President Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  boroughBoardReview: trait({
    milestone: '963beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Borough Board Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 50,
    displayName: 'Borough Board Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  cityPlanningCommissionReview: trait({
    milestone: '9e3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'City Planning Commission Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 54,
    displayName: 'City Planning Commission Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  cityPlanningCommissionVote: trait({
    milestone: 'a43beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'City Planning Commission Vote',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 57,
    displayName: 'City Planning Commission Vote',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  cityCouncilReview: trait({
    milestone: 'a63beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'City Council Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 58,
    displayName: 'City Council Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  mayoralReview: trait({
    milestone: 'a83beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Mayoral Review',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 59,
    displayName: 'Mayoral Review',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

  finalLetterSent: trait({
    milestone: 'aa3beec4-dad0-e711-8116-1458d04e2fb8',
    milestonename: 'Approval Letter Sent to Responsible Agency',
    plannedstartdate: null,
    plannedcompletiondate: null,
    actualstartdate: null,
    actualenddate: null,
    statuscode: null,
    milestonesequence: 60,
    displayName: 'Approval Letter Sent to Responsible Agency',
    displayDate: null,
    displayDate2: null,
    milestoneoutcome: null,
    milestoneLinks: [],
  }),

});
