export const KEYS = [
  'applicantteam',
  'applicants',
  'dcp_name',
  'dcp_applicanttype',
  'dcp_borough',
  'dcp_ceqrnumber',
  'dcp_ceqrtype',
  'dcp_certifiedreferred',
  'dcp_femafloodzonea',
  'dcp_femafloodzoneshadedx',
  'dcp_sisubdivision',
  'dcp_sischoolseat',
  'dcp_projectbrief',
  'dcp_projectid',
  'dcp_projectname',
  'dcp_publicstatus',
  'dcp_publicstatus_simp',
  'dcp_projectcompleted',
  'dcp_hiddenprojectmetrictarget',
  'dcp_ulurp_nonulurp',
  'dcp_validatedcommunitydistricts',
  'has_centroid',
  'dcp_bsanumber',
  'dcp_wrpnumber',
  'dcp_lpcnumber',
  'dcp_name',
  'dcp_lastmilestonedate',
  'dcp_nydospermitnumber',
  'bbls',
  'bbl_featurecollection',
  'addresses',
  'keywords',
  'ulurpnumbers',
  'center',
  'lastmilestonedate',
  'video_links',

  '_dcp_applicant_customer_value',
  '_dcp_applicantadministrator_customer_value',

  // relationships
  'actions',
  'milestones',
  'dispositions',
  'packages',
  'artifacts',
];

export const ACTION_KEYS = [
  'dcp_action',
  'dcp_name',
  'actioncode',
  'statuscode',
  'statecode',
  'dcp_ulurpnumber',
  'dcp_zoningresolution',
  'dcp_ccresolutionnumber',
  '_dcp_action_value',
  '_dcp_zoningresolution_value',
  'dcp_spabsoluteurl',
];

export const MILESTONE_KEYS = [
  'dcp_milestone',
  'dcp_name',
  'milestonename',
  'dcp_plannedstartdate',
  'dcp_plannedcompletiondate',
  'dcp_actualstartdate',
  'dcp_actualenddate',
  'statuscode',
  'dcp_milestonesequence',
  'dcp_remainingplanneddayscalculated',
  'dcp_remainingplanneddays',
  'dcp_goalduration',
  'dcp_actualdurationasoftoday',
  'display_description',
  'display_name',
  'display_date',
  'display_date2',
  'outcome',
  'milestone_links',
  'is_revised',
  'dcp_reviewmeetingdate',
];
